version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"   # Maps Nginx port 80 to localhost:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002" # Expose backend service on port 5002
    environment:
      - NODE_ENV=production
      - PORT=5002
    volumes:
      - ./backend:/app   # For development, bind mount backend code
      - /app/node_modules # Ensures node_modules are managed within container
